locale : en-US
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
github: [metadata]

title: /Users/mrinmoy
description: Mrinmoy's home
name: Mrinmoy Das

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
words_per_minute: 200

author:
  name          : Mrinmoy Das
  avatar        : /assets/images/profile.jpg
  bio           : Web stuff, mostly backend
  github        : goromlagche
  linkedin      : mrinmoy-das-3035387b
  stackoverflow : 2365673/goromlagche
  twitter       : goromlagche

repository: goromlagche/goromlagche.github.io
comments:
  provider: "utterances"
  utterances:
    theme      : github-light
    issue_term : pathname

tag_archive:
  type: liquid
  path: /tags/

paginate: 5
paginate_path: /blog/page:num

search              : true
search_full_content : true
search_provider     : lunr

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      permalink: /blog/:year/:month/:day/:title.html

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jeky-seo-tag
  - jemoji

include:
  - _pages

analytics:
  provider: google
  google:
    tracking_id : UA-44848115-1

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
